runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files: 
    - .env

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  APP_KEY: base64:H7+L+53SWgfMB6LFuNoZZcJG35yZ7eaqbhiRycpXggQ=
  STORAGE_DIR: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  ## Set these environment variables according to your CloudSQL configuration.
  DB_HOST: 130.211.82.52
  DB_DATABASE: wwd
  DB_USERNAME: root
  DB_PASSWORD: tyeeC9NG8nFME8l3
  DB_SOCKET: "/cloudsql/wwdv2-180713:europe-west1:wwd-mysql"
  
beta_settings:
    # for Cloud SQL, set this value to the Cloud SQL connection name,
    # e.g. "project:region:cloudsql-instance"
    cloud_sql_instances: "wwdv2-180713:europe-west1:wwd-mysql"